# ============================================================
# src/config/config.yaml — Configuración general del bot
# ------------------------------------------------------------
# Este archivo define todos los parámetros operativos del bot
# que no deben estar hardcodeados en el código fuente.
#
# 🧭 Objetivo:
#   - Mantener el código limpio, modular y reproducible
#   - Cambiar modo, símbolo, estrategia o parámetros sin editar Python
#
# ⚙️ Cómo se usa:
#   Se carga desde el Engine u otros módulos con pyyaml:
#       import yaml
#       with open("src/config/config.yaml", "r") as f:
#           config = yaml.safe_load(f)
#           print(config["trading"]["symbol"])
#
# ============================================================

# ============================================================
# ENTORNO
# ------------------------------------------------------------
# Define el tipo de ejecución y los modos de conexión
# ============================================================
environment:
  use_testnet: true         # Usa Binance Testnet si True
  mode: "simulation"        # simulation | paper | live
  log_level: "DEBUG"        # Nivel de logs por defecto
  timezone: "Europe/Madrid" # Para timestamps y gráficos

# ============================================================
# TRADING
# ------------------------------------------------------------
# Configuración del activo y comportamiento base
# ============================================================
trading:
  symbol: "BTCUSDT"         # Par principal
  base_asset: "BTC"
  quote_asset: "USDT"
  interval: "1s"            # Frecuencia de actualización (temporal o lógica)
  cycle_delay: 1.0          # Tiempo entre ciclos de decisión (segundos)
  min_notional: 5           # Mínimo de operación (USD)
  trade_fee_bps: 2          # Comisión (en basis points)
  slippage_bps: 5           # Estimación de slippage (en basis points)
  max_position_usd: 200     # Límite de posición total en USD

# ============================================================
# ESTRATEGIA
# ------------------------------------------------------------
# Parámetros específicos de la estrategia actual
# ============================================================
strategy:
  name: "momentum"          # momentum | mean_reversion | custom
  lookback_ticks: 50        # nº de ticks para calcular señal
  entry_threshold: 0.001    # umbral de entrada (%)
  exit_threshold: 0.0005    # umbral de salida (%)
  stop_loss_pct: 0.002      # stop loss 0.2%
  take_profit_pct: 0.004    # take profit 0.4%

# ============================================================
# DATOS
# ------------------------------------------------------------
# Configuración de feeds y almacenamiento
# ============================================================
data:
  source: "binance"         # binance | csv | mock
  use_websocket: true       # si False → modo histórico/simulado
  store_raw_ticks: true     # guarda cada tick en /data/raw/
  store_microcandles: true  # guarda microvelas procesadas
  microcandle_type: "volume" # volume | tick | dollar | imbalance

# ============================================================
# RIESGO Y MÉTRICAS
# ------------------------------------------------------------
# Control de exposición y monitorización
# ============================================================
risk:
  max_drawdown_pct: 0.05    # máximo drawdown permitido (5%)
  max_open_trades: 1        # nº máximo de operaciones abiertas
  daily_loss_limit_pct: 0.02 # límite de pérdidas diarias
  equity_curve_log: true    # guardar evolución de equity

metrics:
  use_daily: false          # calcula métricas sobre días (no ticks)
  annualization_days: 252   # días usados para anualizar ratios
  save_summary: true        # genera resumen JSON tras cada sesión
